import domReady from '@wordpress/dom-ready';
import { _x } from '@wordpress/i18n';
import {
	getBlockVariations,
	registerBlockVariation,
	type BlockVariation,
} from '@wordpress/blocks';

import { ChainIcon, UpworkIcon } from './icons';
import { normalizeWpIcon } from '../../utils/icon-lists';

type AnyAttrs = Record<string, unknown>;

type Variation = {
	name: string;
	attributes: AnyAttrs;
	title: string;
	icon?: any;
	isActive?: (blockAttributes: AnyAttrs, variationAttributes: AnyAttrs) => boolean;
};

const variations: Variation[] = [
	{
		name: 'chain',
		attributes: { service: 'chain' },
		title: _x('Chain', 'wordpress-blocks'),
		icon: ChainIcon,
	},
	{
		name: 'upwork',
		attributes: { service: 'upwork' },
		title: _x('Upwork', 'wordpress-blocks'),
		icon: UpworkIcon,
	},
];

variations.forEach((variation) => {
	if (variation.isActive) return;
	variation.isActive = (blockAttributes, variationAttributes) =>
		(blockAttributes as any).service === (variationAttributes as any).service;
});

export default variations;

domReady(() => {
	const toTitleCase = (str: string) =>
		str
			.replace(/[^a-zA-Z0-9]+/g, ' ')
			.trim()
			.replace(/\s+/g, ' ')
			.replace(/\b\w/g, (c) => c.toUpperCase());

	const Dashicon = ({ slug }: { slug: string }) => (
		<span className={`dashicons dashicons-${slug}`} />
	);

	const isActive = (blockAttributes: AnyAttrs, variationAttributes: AnyAttrs) =>
		(blockAttributes as any).service === (variationAttributes as any).service;

	type ZiorVariation = Pick<BlockVariation, 'name' | 'title' | 'icon' | 'attributes'> & {
		name: string;
		title: string;
		icon: any;
		attributes: AnyAttrs;
	};

	const allVariations: ZiorVariation[] = [];

	// Core social-link variations
	const socialVariations = getBlockVariations('core/social-link') ?? [];

	socialVariations.forEach((variation) => {
		const v = variation as any;

		const iconValue =
			typeof v.icon === 'function'
				? v.icon // keep function (do NOT call)
				: normalizeWpIcon(v.icon);

		allVariations.push({
			name: String(v.name),
			title: String(v.title ?? v.name ?? ''),
			icon: iconValue,
			attributes: (v.attributes ?? {}) as AnyAttrs,
		});
	});

	const dashIcons: string[] = [
		'admin-appearance',
		'admin-collapse',
		'admin-comments',
		'admin-customizer',
		'admin-generic',
		'admin-home',
		'admin-links',
		'admin-media',
		'admin-multisite',
		'admin-network',
		'admin-page',
		'admin-plugins',
		'admin-post',
		'admin-settings',
		'admin-site',
		'admin-site-alt',
		'admin-site-alt2',
		'admin-site-alt3',
		'admin-tools',
		'admin-users',
		'airplane',
		'album',
		'align-center',
		'align-full-width',
		'align-left',
		'align-none',
		'align-pull-left',
		'align-pull-right',
		'align-right',
		'align-wide',
		'analytics',
		'archive',
		'arrow-down',
		'arrow-down-alt',
		'arrow-down-alt2',
		'arrow-left',
		'arrow-left-alt',
		'arrow-left-alt2',
		'arrow-right',
		'arrow-right-alt',
		'arrow-right-alt2',
		'arrow-up',
		'arrow-up-alt',
		'arrow-up-alt2',
		'arrow-up-duplicate',
		'art',
		'awards',
		'backup',
		'bank',
		'beer',
		'bell',
		'block-default',
		'book',
		'book-alt',
		'buddicons-activity',
		'buddicons-bbpress-logo',
		'buddicons-buddypress-logo',
		'buddicons-community',
		'buddicons-forums',
		'buddicons-friends',
		'buddicons-groups',
		'buddicons-pm',
		'buddicons-replies',
		'buddicons-topics',
		'buddicons-tracking',
		'building',
		'businessman',
		'businessperson',
		'businesswoman',
		'button',
		'calculator',
		'calendar',
		'calendar-alt',
		'camera',
		'camera-alt',
		'car',
		'carrot',
		'cart',
		'category',
		'chart-area',
		'chart-bar',
		'chart-line',
		'chart-pie',
		'clipboard',
		'clock',
		'cloud',
		'cloud-saved',
		'cloud-upload',
		'code-standards',
		'coffee',
		'color-picker',
		'columns',
		'controls-back',
		'controls-forward',
		'controls-pause',
		'controls-play',
		'controls-repeat',
		'controls-skipback',
		'controls-skipforward',
		'controls-volumeoff',
		'controls-volumeon',
		'cover-image',
		'dashboard',
		'database',
		'database-add',
		'database-export',
		'database-import',
		'database-remove',
		'database-view',
		'desktop',
		'dismiss',
		'download',
		'drumstick',
		'edit',
		'editor-aligncenter',
		'editor-alignleft',
		'editor-alignright',
		'editor-bold',
		'editor-break',
		'editor-code',
		'editor-code-duplicate',
		'editor-contract',
		'editor-customchar',
		'editor-distractionfree',
		'editor-expand',
		'editor-help',
		'editor-indent',
		'editor-insertmore',
		'editor-italic',
		'editor-justify',
		'editor-kitchensink',
		'editor-ltr',
		'editor-ol',
		'editor-ol-rtl',
		'editor-outdent',
		'editor-paragraph',
		'editor-paste-text',
		'editor-paste-word',
		'editor-quote',
		'editor-removeformatting',
		'editor-rtl',
		'editor-spellcheck',
		'editor-strikethrough',
		'editor-table',
		'editor-textcolor',
		'editor-ul',
		'editor-underline',
		'editor-unlink',
		'editor-video',
		'edit-large',
		'edit-page',
		'ellipsis',
		'email',
		'email-alt',
		'email-alt2',
		'embed-audio',
		'embed-generic',
		'embed-photo',
		'embed-post',
		'embed-video',
		'excerpt-view',
		'exerpt-view',
		'exit',
		'external',
		'facebook-alt',
		'feedback',
		'filter',
		'flag',
		'food',
		'format-aside',
		'format-audio',
		'format-chat',
		'format-gallery',
		'format-image',
		'format-links',
		'format-quote',
		'format-standard',
		'format-status',
		'format-video',
		'forms',
		'fullscreen-alt',
		'fullscreen-exit-alt',
		'games',
		'googleplus',
		'grid-view',
		'groups',
		'hammer',
		'heading',
		'heart',
		'hidden',
		'hourglass',
		'html',
		'id',
		'id-alt',
		'images-alt',
		'images-alt2',
		'image-crop',
		'image-filter',
		'image-flip-horizontal',
		'image-flip-vertical',
		'image-rotate',
		'image-rotate-left',
		'image-rotate-right',
		'index-card',
		'info',
		'info-outline',
		'insert',
		'insert-after',
		'insert-before',
		'laptop',
		'layout',
		'leftright',
		'lightbulb',
		'linkedin',
		'list-view',
		'location',
		'location-alt',
		'lock',
		'lock-duplicate',
		'marker',
		'media-archive',
		'media-audio',
		'media-code',
		'media-default',
		'media-document',
		'media-interactive',
		'media-spreadsheet',
		'media-text',
		'media-video',
		'megaphone',
		'menu',
		'menu-alt',
		'menu-alt2',
		'menu-alt3',
		'microphone',
		'migrate',
		'minus',
		'money',
		'money-alt',
		'move',
		'nametag',
		'networking',
		'no',
		'no-alt',
		'open-folder',
		'palmtree',
		'paperclip',
		'pdf',
		'performance',
		'pets',
		'phone',
		'pinterest',
		'playlist-audio',
		'playlist-video',
		'plugins-checked',
		'plus',
		'plus-alt',
		'plus-alt2',
		'podio',
		'portfolio',
		'post-status',
		'post-trash',
		'pressthis',
		'printer',
		'privacy',
		'products',
		'randomize',
		'redo',
		'remove',
		'rest-api',
		'rss',
		'saved',
		'schedule',
		'screenoptions',
		'search',
		'share',
		'share1',
		'share-alt',
		'share-alt2',
		'shield',
		'shield-alt',
		'shortcode',
		'slides',
		'smartphone',
		'smiley',
		'sort',
		'sos',
		'star-empty',
		'star-filled',
		'star-half',
		'sticky',
		'store',
		'superhero',
		'superhero-alt',
		'tablet',
		'table-col-after',
		'table-col-before',
		'table-col-delete',
		'table-row-after',
		'table-row-before',
		'table-row-delete',
		'tag',
		'tagcloud',
		'testimonial',
		'text',
		'text-page',
		'thumbs-down',
		'thumbs-up',
		'tickets',
		'tickets-alt',
		'tide',
		'translation',
		'trash',
		'twitter-alt',
		'undo',
		'universal-access',
		'universal-access-alt',
		'unlock',
		'update',
		'update-alt',
		'upload',
		'vault',
		'video-alt',
		'video-alt2',
		'video-alt3',
		'visibility',
		'warning',
		'welcome-add-page',
		'welcome-comments',
		'welcome-edit-page',
		'welcome-learn-more',
		'welcome-view-site',
		'welcome-widgets-menus',
		'welcome-write-blog',
		'xing',
		'yes',
		'yes-alt',
	];

	dashIcons.forEach((slug) => {
		allVariations.push({
			name: slug,
			title: toTitleCase(slug),
			icon: <Dashicon slug={slug} />,
			attributes: { service: slug },
		});
	});

	allVariations.forEach((variation) => {
		registerBlockVariation('zior/icon', { ...variation, isActive });
	});
});
